obstacle_range: 10 # 3.0
raytrace_range: 20 # 3.5

#footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
  #[[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
robot_radius: 0.75

inflation_radius:  2.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
