map_update_interval: 2.0
maxUrange: 20.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 100 # 50 GRAEME trying to discourage the big jumps
srr: 0.1 # 0.1
srt: 0.05 # 0.2
str: 0.05 # 0.1
stt: 0.1 # 0.2
linearUpdate: 0.5 # 1.0
angularUpdate: 0.2
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 200 #100
xmin: -10.0 # size of map
ymin: -10.0
xmax: 80.0
ymax: 80.0
delta: 0.1 # resolution of grid cell
llsamplerange: 0.01 #0.01
llsamplestep: 0.01 # 0.01
lasamplerange: 0.005 # 0.005
lasamplestep: 0.005 # 0.005
